# Generated by Django 5.1.5 on 2025-01-29 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='tumor_Img',
            field=models.ImageField(upload_to='tumor_images/'),
        ),
    ]
